### PR TITLE
Access individual components

### PR DESCRIPTION
**Pull request by dlecocq**
Previously these were treated as private members, but as discussed in #18 we are comfortable making these public.

@b4hand @arora-richa @neilmb

### CODE REVIEW

**Comment by b4hand** [comment]
It seems like if you're going to expose member data directly, then you may want to convert some of the existing methods into dynamic attributes like `pld()`, `tld()`, etc.

Also, I think you need to address the issue of methods that mutate the underlying members and how that can spread to other objects. It might be good to provide a clone method or copy constructor to avoid implicit data sharing.

**Comment by dlecocq** [comment]
Yeah. How does this sound for a convention -- methods that return a `url` object (the chainable things) will remain methods, but methods that return something other than a `url` will be turned into `properties`?

I'm not sure there's much risk for a data sharing, but we could provide `__copy__` and `__deepcopy__`

**Comment by b4hand** [comment]
That sounds reasonable to me.

**Comment by dlecocq** [comment]
@b4hand -- comments addressed

Since this included API-breaking changes, version bump to `0.2.0`

**Pull request merged**
