### PR TITLE
Support Python 3

### PR DESCRIPTION
**Pull request by dlecocq**
This is because `reppy` would like to potentially use `url-py`, and `reppy` has thus far maintained support for python 3.

@b4hand @lindseyreno @neilmb

### CODE REVIEW

**Comment by dlecocq** [comment]
It's also worth noting that I'm not in love with any particular piece of this, especially in terms of the implementation -- all the type checks are driving me a little nuts, but that might just be what we need.

**Comment by b4hand** [comment]
I think you can fix the test failure by escaping the literal é as `\u00e9` on line 179 of test.py.

**Comment by dlecocq** [comment]
In the end, I couldn't just pass things to the `str` constructor. A detail from the docs is that without either `encoding` or `errors`, the behavior of the `str` constructor is to call `__str__` on the passed-in object. This subclassing approach felt more elegant as it requires only a single type check, at import time.

**Comment by dlecocq** [comment]
Another nice aspect of this approach is that both bits of functionality are accessible from python 2 or 3.

**Comment by b4hand** [comment]
In the long run this version is probably better than the prior.

**Pull request merged**
